### ISSUE TITLE
uploadChunk function not found error when uploading large files during doAzureParallel processing

### ISSUE THREAD

**Issue by CS15B061** [Azure/rAzureBatch#58]
https://github.com/Azure/rAzureBatch/blob/a730240b4c5a0429547f044af891141d008e7766/R/blob_operations.R#L121

When I tried to do parallel processing in larger size objects, I found error:

`Error in uploadChunk(containerName, fileDirectory, content = content,  :
  could not find function "uploadChunk"`

When I went to R/blob_operations.R I found that uploadChunk function is used but not called with self$uploadChunk

**Comment by CS15B061** [comment]
When I rectified the error in cloned copy and run it I get 'az_config' File does not exist. What exactly is the file and where can I get it?

**Comment by brnleehng** [comment]
Hi @CS15B061 

Sorry for not looking into this sooner. We are much more active in the doAzureParallel repo since most of our users look into doAzureParallel. UploadChunk is a helper function to divide large files into multiple files in order to upload it to Azure Storage. az_config is a configuration file default name. I will take a look to repro this

Thanks,
Brian

**Comment by brnleehng** [comment]
Hi @CS15B061 

I found the issue of the UploadChunk not working because of missing authentication.

Thanks,
Brian

**Comment by brnleehng** [comment]
Hi @CS15B061 ,

I've updated the rAzureBatch package.

Thanks,
Brian
